//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.default_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadNorthTouch
        {
            get
            {
                return SteamVR_Actions.default_PadNorthTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadEastTouch
        {
            get
            {
                return SteamVR_Actions.default_PadEastTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadSouthTouch
        {
            get
            {
                return SteamVR_Actions.default_PadSouthTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadWestTouch
        {
            get
            {
                return SteamVR_Actions.default_PadWestTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadNorthClick
        {
            get
            {
                return SteamVR_Actions.default_PadNorthClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadEastClick
        {
            get
            {
                return SteamVR_Actions.default_PadEastClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadSouthClick
        {
            get
            {
                return SteamVR_Actions.default_PadSouthClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadWestClick
        {
            get
            {
                return SteamVR_Actions.default_PadWestClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadCenterTouch
        {
            get
            {
                return SteamVR_Actions.default_PadCenterTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadCenterClick
        {
            get
            {
                return SteamVR_Actions.default_PadCenterClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PadPosition
        {
            get
            {
                return SteamVR_Actions.default_PadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuClick
        {
            get
            {
                return SteamVR_Actions.default_MenuClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickClick
        {
            get
            {
                return SteamVR_Actions.default_JoystickClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickPosition
        {
            get
            {
                return SteamVR_Actions.default_JoystickPosition;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
